-- ============================================
-- Varsayılan Sayfalar (Default Pages)
-- TeknoProje Platformu için hazır şablon sayfalar
-- ============================================

-- Mevcut sayfaları sil (isteğe bağlı - yorum satırını kaldırarak aktif edebilirsiniz)
-- DELETE FROM content_translations WHERE content_type = 'page' AND content_id IN (SELECT id FROM pages WHERE slug IN ('hakkimizda', 'gizlilik-politikamiz', 'hizmet-sozlesmesi', 'misyon-vizyon', 'kalite-politikamiz', 'teslimat-ve-iade-sartlari', 'cerez-politikasi', 'lisans-politikasi'));
-- DELETE FROM pages WHERE slug IN ('hakkimizda', 'gizlilik-politikamiz', 'hizmet-sozlesmesi', 'misyon-vizyon', 'kalite-politikamiz', 'teslimat-ve-iade-sartlari', 'cerez-politikasi', 'lisans-politikasi');

-- 1. Hakkımızda
INSERT INTO `pages` (`title`, `slug`, `content`, `meta_title`, `meta_description`, `status`) VALUES
('Hakkımızda', 'hakkimizda', '<div class="page-content"><h2>TeknoProje\'ye Hoş Geldiniz</h2><p>TeknoProje, yazılım geliştirme projelerini bir araya getiren modern bir platformdur. 2020 yılından beri faaliyet gösteren ekibimiz, kaliteli yazılım çözümleri sunmak için çalışmaktadır.</p><h3>Vizyonumuz</h3><p>Teknoloji dünyasında öncü bir platform olmak ve yazılım geliştiricileri ile ihtiyaç sahiplerini buluşturmak.</p><h3>Değerlerimiz</h3><ul><li>Kalite odaklı yaklaşım</li><li>Müşteri memnuniyeti</li><li>İnovasyon ve yenilikçilik</li><li>Şeffaflık ve güven</li></ul></div>', 'Hakkımızda - TeknoProje', 'TeknoProje hakkında bilgi edinin. Vizyonumuz, misyonumuz ve değerlerimiz.', 'active')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `content` = VALUES(`content`),
    `meta_title` = VALUES(`meta_title`),
    `meta_description` = VALUES(`meta_description`),
    `status` = VALUES(`status`);

SET @page_id_1 = (SELECT id FROM pages WHERE slug = 'hakkimizda' LIMIT 1);

INSERT INTO `content_translations` (`content_id`, `content_type`, `language_code`, `title`, `description`) VALUES
(@page_id_1, 'page', 'tr', 'Hakkımızda', '<div class="page-content"><h2>TeknoProje\'ye Hoş Geldiniz</h2><p>TeknoProje, yazılım geliştirme projelerini bir araya getiren modern bir platformdur. 2020 yılından beri faaliyet gösteren ekibimiz, kaliteli yazılım çözümleri sunmak için çalışmaktadır.</p><h3>Vizyonumuz</h3><p>Teknoloji dünyasında öncü bir platform olmak ve yazılım geliştiricileri ile ihtiyaç sahiplerini buluşturmak.</p><h3>Değerlerimiz</h3><ul><li>Kalite odaklı yaklaşım</li><li>Müşteri memnuniyeti</li><li>İnovasyon ve yenilikçilik</li><li>Şeffaflık ve güven</li></ul></div>'),
(@page_id_1, 'page', 'en', 'About Us', '<div class="page-content"><h2>Welcome to TeknoProje</h2><p>TeknoProje is a modern platform that brings together software development projects. Our team, which has been operating since 2020, works to provide quality software solutions.</p><h3>Our Vision</h3><p>To be a leading platform in the technology world and bring together software developers and those in need.</p><h3>Our Values</h3><ul><li>Quality-focused approach</li><li>Customer satisfaction</li><li>Innovation and creativity</li><li>Transparency and trust</li></ul></div>'),
(@page_id_1, 'page', 'de', 'Über Uns', '<div class="page-content"><h2>Willkommen bei TeknoProje</h2><p>TeknoProje ist eine moderne Plattform, die Softwareentwicklungsprojekte zusammenbringt. Unser Team, das seit 2020 tätig ist, arbeitet daran, qualitativ hochwertige Softwarelösungen anzubieten.</p><h3>Unsere Vision</h3><p>Eine führende Plattform in der Technologiewelt zu sein und Softwareentwickler mit Bedürftigen zusammenzubringen.</p><h3>Unsere Werte</h3><ul><li>Qualitätsorientierter Ansatz</li><li>Kundenzufriedenheit</li><li>Innovation und Kreativität</li><li>Transparenz und Vertrauen</li></ul></div>')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `description` = VALUES(`description`);

-- 2. Gizlilik Politikamız
INSERT INTO `pages` (`title`, `slug`, `content`, `meta_title`, `meta_description`, `status`) VALUES
('Gizlilik Politikamız', 'gizlilik-politikamiz', '<div class="page-content"><h2>Gizlilik Politikamız</h2><p>Son güncelleme: 2024</p><h3>Kişisel Verilerin Toplanması</h3><p>Platformumuzda topladığımız kişisel veriler şunlardır: ad, soyad, e-posta adresi, telefon numarası ve ödeme bilgileri. Bu veriler, hizmetlerimizi sunmak ve geliştirmek için kullanılmaktadır.</p><h3>Verilerin Kullanımı</h3><p>Toplanan veriler sadece aşağıdaki amaçlar için kullanılır:</p><ul><li>Hesap yönetimi ve sipariş işlemleri</li><li>Müşteri desteği sağlama</li><li>Platform geliştirme ve iyileştirme</li><li>Yasal yükümlülüklerin yerine getirilmesi</li></ul><h3>Veri Güvenliği</h3><p>Tüm kişisel verileriniz SSL şifreleme ile korunmaktadır. Verilerinize yetkisiz erişimi önlemek için gerekli teknik ve idari önlemleri almaktayız.</p><h3>Çerezler</h3><p>Platformumuz, kullanıcı deneyimini iyileştirmek için çerezler kullanmaktadır. Detaylı bilgi için Çerez Politikamız sayfasını ziyaret edebilirsiniz.</p><h3>Haklarınız</h3><p>KVKK kapsamında, kişisel verilerinizle ilgili aşağıdaki haklara sahipsiniz:</p><ul><li>Erişim hakkı</li><li>Düzeltme hakkı</li><li>Silme hakkı</li><li>İtiraz hakkı</li></ul></div>', 'Gizlilik Politikamız - TeknoProje', 'TeknoProje gizlilik politikası. Kişisel verilerinizin nasıl toplandığı, kullanıldığı ve korunduğu hakkında bilgi.', 'active')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `content` = VALUES(`content`),
    `meta_title` = VALUES(`meta_title`),
    `meta_description` = VALUES(`meta_description`),
    `status` = VALUES(`status`);

SET @page_id_2 = (SELECT id FROM pages WHERE slug = 'gizlilik-politikamiz' LIMIT 1);

INSERT INTO `content_translations` (`content_id`, `content_type`, `language_code`, `title`, `description`) VALUES
(@page_id_2, 'page', 'tr', 'Gizlilik Politikamız', '<div class="page-content"><h2>Gizlilik Politikamız</h2><p>Son güncelleme: 2024</p><h3>Kişisel Verilerin Toplanması</h3><p>Platformumuzda topladığımız kişisel veriler şunlardır: ad, soyad, e-posta adresi, telefon numarası ve ödeme bilgileri. Bu veriler, hizmetlerimizi sunmak ve geliştirmek için kullanılmaktadır.</p><h3>Verilerin Kullanımı</h3><p>Toplanan veriler sadece aşağıdaki amaçlar için kullanılır:</p><ul><li>Hesap yönetimi ve sipariş işlemleri</li><li>Müşteri desteği sağlama</li><li>Platform geliştirme ve iyileştirme</li><li>Yasal yükümlülüklerin yerine getirilmesi</li></ul><h3>Veri Güvenliği</h3><p>Tüm kişisel verileriniz SSL şifreleme ile korunmaktadır. Verilerinize yetkisiz erişimi önlemek için gerekli teknik ve idari önlemleri almaktayız.</p><h3>Çerezler</h3><p>Platformumuz, kullanıcı deneyimini iyileştirmek için çerezler kullanmaktadır. Detaylı bilgi için Çerez Politikamız sayfasını ziyaret edebilirsiniz.</p><h3>Haklarınız</h3><p>KVKK kapsamında, kişisel verilerinizle ilgili aşağıdaki haklara sahipsiniz:</p><ul><li>Erişim hakkı</li><li>Düzeltme hakkı</li><li>Silme hakkı</li><li>İtiraz hakkı</li></ul></div>'),
(@page_id_2, 'page', 'en', 'Privacy Policy', '<div class="page-content"><h2>Privacy Policy</h2><p>Last updated: 2024</p><h3>Collection of Personal Data</h3><p>The personal data we collect on our platform includes: name, surname, email address, phone number, and payment information. This data is used to provide and improve our services.</p><h3>Use of Data</h3><p>Collected data is only used for the following purposes:</p><ul><li>Account management and order processing</li><li>Providing customer support</li><li>Platform development and improvement</li><li>Fulfilling legal obligations</li></ul><h3>Data Security</h3><p>All your personal data is protected with SSL encryption. We take necessary technical and administrative measures to prevent unauthorized access to your data.</p><h3>Cookies</h3><p>Our platform uses cookies to improve user experience. For detailed information, you can visit our Cookie Policy page.</p><h3>Your Rights</h3><p>Under GDPR, you have the following rights regarding your personal data:</p><ul><li>Right of access</li><li>Right to rectification</li><li>Right to erasure</li><li>Right to object</li></ul></div>'),
(@page_id_2, 'page', 'de', 'Datenschutzerklärung', '<div class="page-content"><h2>Datenschutzerklärung</h2><p>Letzte Aktualisierung: 2024</p><h3>Erhebung personenbezogener Daten</h3><p>Die personenbezogenen Daten, die wir auf unserer Plattform sammeln, umfassen: Name, Nachname, E-Mail-Adresse, Telefonnummer und Zahlungsinformationen. Diese Daten werden verwendet, um unsere Dienstleistungen bereitzustellen und zu verbessern.</p><h3>Verwendung von Daten</h3><p>Gesammelte Daten werden nur für folgende Zwecke verwendet:</p><ul><li>Kontoverwaltung und Bestellabwicklung</li><li>Bereitstellung von Kundensupport</li><li>Plattformentwicklung und -verbesserung</li><li>Erfüllung rechtlicher Verpflichtungen</li></ul><h3>Datensicherheit</h3><p>Alle Ihre personenbezogenen Daten sind durch SSL-Verschlüsselung geschützt. Wir ergreifen die notwendigen technischen und administrativen Maßnahmen, um unbefugten Zugriff auf Ihre Daten zu verhindern.</p><h3>Cookies</h3><p>Unsere Plattform verwendet Cookies, um die Benutzererfahrung zu verbessern. Weitere Informationen finden Sie auf unserer Cookie-Richtlinienseite.</p><h3>Ihre Rechte</h3><p>Unter DSGVO haben Sie folgende Rechte bezüglich Ihrer personenbezogenen Daten:</p><ul><li>Recht auf Auskunft</li><li>Recht auf Berichtigung</li><li>Recht auf Löschung</li><li>Widerspruchsrecht</li></ul></div>')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `description` = VALUES(`description`);

-- 3. Hizmet Sözleşmesi
INSERT INTO `pages` (`title`, `slug`, `content`, `meta_title`, `meta_description`, `status`) VALUES
('Hizmet Sözleşmesi', 'hizmet-sozlesmesi', '<div class="page-content"><h2>Hizmet Sözleşmesi</h2><p>Son güncelleme: 2024</p><h3>1. Genel Hükümler</h3><p>Bu hizmet sözleşmesi, TeknoProje platformunun kullanımı ile ilgili tüm hak ve yükümlülükleri düzenlemektedir. Platformu kullanarak bu sözleşmeyi kabul etmiş sayılırsınız.</p><h3>2. Hizmetler</h3><p>TeknoProje platformu aşağıdaki hizmetleri sunmaktadır:</p><ul><li>Yazılım projelerinin satışı</li><li>Proje geliştirme hizmetleri</li><li>Danışmanlık hizmetleri</li><li>Teknik destek</li></ul><h3>3. Kullanıcı Yükümlülükleri</h3><p>Kullanıcılar, platformu yasalara uygun şekilde kullanmakla yükümlüdür. Aşağıdaki faaliyetler yasaktır:</p><ul><li>Telif hakkı ihlali</li><li>Spam veya kötü amaçlı içerik paylaşımı</li><li>Diğer kullanıcıları aldatma</li><li>Platform güvenliğini tehdit etme</li></ul><h3>4. Ödeme ve İade</h3><p>Ödeme işlemleri güvenli ödeme sistemleri üzerinden gerçekleştirilir. İade politikası için Teslimat ve İade Şartları sayfasını inceleyebilirsiniz.</p><h3>5. Sorumluluk Sınırlaması</h3><p>Platform, kullanıcıların paylaştığı içeriklerden sorumlu değildir. Kullanıcılar kendi içeriklerinden sorumludur.</p></div>', 'Hizmet Sözleşmesi - TeknoProje', 'TeknoProje hizmet sözleşmesi. Platform kullanım şartları ve kullanıcı yükümlülükleri.', 'active')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `content` = VALUES(`content`),
    `meta_title` = VALUES(`meta_title`),
    `meta_description` = VALUES(`meta_description`),
    `status` = VALUES(`status`);

SET @page_id_3 = (SELECT id FROM pages WHERE slug = 'hizmet-sozlesmesi' LIMIT 1);

INSERT INTO `content_translations` (`content_id`, `content_type`, `language_code`, `title`, `description`) VALUES
(@page_id_3, 'page', 'tr', 'Hizmet Sözleşmesi', '<div class="page-content"><h2>Hizmet Sözleşmesi</h2><p>Son güncelleme: 2024</p><h3>1. Genel Hükümler</h3><p>Bu hizmet sözleşmesi, TeknoProje platformunun kullanımı ile ilgili tüm hak ve yükümlülükleri düzenlemektedir. Platformu kullanarak bu sözleşmeyi kabul etmiş sayılırsınız.</p><h3>2. Hizmetler</h3><p>TeknoProje platformu aşağıdaki hizmetleri sunmaktadır:</p><ul><li>Yazılım projelerinin satışı</li><li>Proje geliştirme hizmetleri</li><li>Danışmanlık hizmetleri</li><li>Teknik destek</li></ul><h3>3. Kullanıcı Yükümlülükleri</h3><p>Kullanıcılar, platformu yasalara uygun şekilde kullanmakla yükümlüdür. Aşağıdaki faaliyetler yasaktır:</p><ul><li>Telif hakkı ihlali</li><li>Spam veya kötü amaçlı içerik paylaşımı</li><li>Diğer kullanıcıları aldatma</li><li>Platform güvenliğini tehdit etme</li></ul><h3>4. Ödeme ve İade</h3><p>Ödeme işlemleri güvenli ödeme sistemleri üzerinden gerçekleştirilir. İade politikası için Teslimat ve İade Şartları sayfasını inceleyebilirsiniz.</p><h3>5. Sorumluluk Sınırlaması</h3><p>Platform, kullanıcıların paylaştığı içeriklerden sorumlu değildir. Kullanıcılar kendi içeriklerinden sorumludur.</p></div>'),
(@page_id_3, 'page', 'en', 'Terms of Service', '<div class="page-content"><h2>Terms of Service</h2><p>Last updated: 2024</p><h3>1. General Provisions</h3><p>This terms of service agreement regulates all rights and obligations related to the use of the TeknoProje platform. By using the platform, you are deemed to have accepted this agreement.</p><h3>2. Services</h3><p>The TeknoProje platform offers the following services:</p><ul><li>Sale of software projects</li><li>Project development services</li><li>Consulting services</li><li>Technical support</li></ul><h3>3. User Obligations</h3><p>Users are obliged to use the platform in accordance with the law. The following activities are prohibited:</p><ul><li>Copyright infringement</li><li>Sharing spam or malicious content</li><li>Deceiving other users</li><li>Threatening platform security</li></ul><h3>4. Payment and Refund</h3><p>Payment transactions are carried out through secure payment systems. You can review the Delivery and Refund Terms page for the refund policy.</p><h3>5. Limitation of Liability</h3><p>The platform is not responsible for content shared by users. Users are responsible for their own content.</p></div>'),
(@page_id_3, 'page', 'de', 'Nutzungsbedingungen', '<div class="page-content"><h2>Nutzungsbedingungen</h2><p>Letzte Aktualisierung: 2024</p><h3>1. Allgemeine Bestimmungen</h3><p>Diese Nutzungsbedingungen regeln alle Rechte und Pflichten im Zusammenhang mit der Nutzung der TeknoProje-Plattform. Durch die Nutzung der Plattform gelten Sie als akzeptiert.</p><h3>2. Dienstleistungen</h3><p>Die TeknoProje-Plattform bietet folgende Dienstleistungen an:</p><ul><li>Verkauf von Softwareprojekten</li><li>Projektentwicklungsdienstleistungen</li><li>Beratungsdienstleistungen</li><li>Technischer Support</li></ul><h3>3. Benutzerpflichten</h3><p>Benutzer sind verpflichtet, die Plattform gesetzeskonform zu nutzen. Folgende Aktivitäten sind verboten:</p><ul><li>Urheberrechtsverletzung</li><li>Verbreitung von Spam oder bösartigen Inhalten</li><li>Täuschung anderer Benutzer</li><li>Bedrohung der Plattformsicherheit</li></ul><h3>4. Zahlung und Rückerstattung</h3><p>Zahlungstransaktionen werden über sichere Zahlungssysteme abgewickelt. Die Rückerstattungsrichtlinie finden Sie auf der Seite Liefer- und Rückerstattungsbedingungen.</p><h3>5. Haftungsbeschränkung</h3><p>Die Plattform ist nicht für von Benutzern geteilte Inhalte verantwortlich. Benutzer sind für ihre eigenen Inhalte verantwortlich.</p></div>')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `description` = VALUES(`description`);

-- 4. Misyon & Vizyon
INSERT INTO `pages` (`title`, `slug`, `content`, `meta_title`, `meta_description`, `status`) VALUES
('Misyon & Vizyon', 'misyon-vizyon', '<div class="page-content"><h2>Misyon & Vizyon</h2><h3>Misyonumuz</h3><p>TeknoProje olarak misyonumuz, yazılım geliştiricileri ile ihtiyaç sahiplerini buluşturarak, kaliteli ve yenilikçi yazılım çözümlerinin erişilebilir olmasını sağlamaktır. Herkesin ihtiyacına uygun yazılım projelerine ulaşabilmesi için çalışıyoruz.</p><h3>Vizyonumuz</h3><p>2025 yılına kadar Türkiye\'nin en büyük yazılım proje platformu olmak ve global pazarda da önemli bir oyuncu haline gelmek. Teknoloji dünyasında sürdürülebilir bir ekosistem oluşturmak.</p><h3>Hedeflerimiz</h3><ul><li>10.000+ aktif kullanıcıya ulaşmak</li><li>5.000+ kaliteli proje sunmak</li><li>%95+ müşteri memnuniyeti sağlamak</li><li>Global pazara açılmak</li></ul><h3>Değerlerimiz</h3><ul><li><strong>Kalite:</strong> Her zaman en yüksek standartları hedefliyoruz</li><li><strong>İnovasyon:</strong> Sürekli gelişim ve yenilikçilik</li><li><strong>Güven:</strong> Şeffaf ve güvenilir hizmet</li><li><strong>Müşteri Odaklılık:</strong> Müşteri memnuniyeti önceliğimiz</li></ul></div>', 'Misyon & Vizyon - TeknoProje', 'TeknoProje misyon ve vizyon. Hedeflerimiz ve değerlerimiz hakkında bilgi.', 'active')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `content` = VALUES(`content`),
    `meta_title` = VALUES(`meta_title`),
    `meta_description` = VALUES(`meta_description`),
    `status` = VALUES(`status`);

SET @page_id_4 = (SELECT id FROM pages WHERE slug = 'misyon-vizyon' LIMIT 1);

INSERT INTO `content_translations` (`content_id`, `content_type`, `language_code`, `title`, `description`) VALUES
(@page_id_4, 'page', 'tr', 'Misyon & Vizyon', '<div class="page-content"><h2>Misyon & Vizyon</h2><h3>Misyonumuz</h3><p>TeknoProje olarak misyonumuz, yazılım geliştiricileri ile ihtiyaç sahiplerini buluşturarak, kaliteli ve yenilikçi yazılım çözümlerinin erişilebilir olmasını sağlamaktır. Herkesin ihtiyacına uygun yazılım projelerine ulaşabilmesi için çalışıyoruz.</p><h3>Vizyonumuz</h3><p>2025 yılına kadar Türkiye\'nin en büyük yazılım proje platformu olmak ve global pazarda da önemli bir oyuncu haline gelmek. Teknoloji dünyasında sürdürülebilir bir ekosistem oluşturmak.</p><h3>Hedeflerimiz</h3><ul><li>10.000+ aktif kullanıcıya ulaşmak</li><li>5.000+ kaliteli proje sunmak</li><li>%95+ müşteri memnuniyeti sağlamak</li><li>Global pazara açılmak</li></ul><h3>Değerlerimiz</h3><ul><li><strong>Kalite:</strong> Her zaman en yüksek standartları hedefliyoruz</li><li><strong>İnovasyon:</strong> Sürekli gelişim ve yenilikçilik</li><li><strong>Güven:</strong> Şeffaf ve güvenilir hizmet</li><li><strong>Müşteri Odaklılık:</strong> Müşteri memnuniyeti önceliğimiz</li></ul></div>'),
(@page_id_4, 'page', 'en', 'Mission & Vision', '<div class="page-content"><h2>Mission & Vision</h2><h3>Our Mission</h3><p>As TeknoProje, our mission is to make quality and innovative software solutions accessible by bringing together software developers and those in need. We work to ensure that everyone can access software projects that meet their needs.</p><h3>Our Vision</h3><p>To become Turkey\'s largest software project platform by 2025 and become a significant player in the global market. To create a sustainable ecosystem in the technology world.</p><h3>Our Goals</h3><ul><li>Reach 10,000+ active users</li><li>Offer 5,000+ quality projects</li><li>Achieve 95%+ customer satisfaction</li><li>Enter the global market</li></ul><h3>Our Values</h3><ul><li><strong>Quality:</strong> We always aim for the highest standards</li><li><strong>Innovation:</strong> Continuous development and innovation</li><li><strong>Trust:</strong> Transparent and reliable service</li><li><strong>Customer Focus:</strong> Customer satisfaction is our priority</li></ul></div>'),
(@page_id_4, 'page', 'de', 'Mission & Vision', '<div class="page-content"><h2>Mission & Vision</h2><h3>Unsere Mission</h3><p>Als TeknoProje ist es unsere Mission, qualitativ hochwertige und innovative Softwarelösungen zugänglich zu machen, indem wir Softwareentwickler mit Bedürftigen zusammenbringen. Wir arbeiten daran, dass jeder auf Softwareprojekte zugreifen kann, die seinen Bedürfnissen entsprechen.</p><h3>Unsere Vision</h3><p>Bis 2025 die größte Softwareprojektplattform der Türkei zu werden und ein bedeutender Akteur auf dem globalen Markt zu werden. Ein nachhaltiges Ökosystem in der Technologiewelt zu schaffen.</p><h3>Unsere Ziele</h3><ul><li>10.000+ aktive Benutzer erreichen</li><li>5.000+ qualitativ hochwertige Projekte anbieten</li><li>95%+ Kundenzufriedenheit erreichen</li><li>In den globalen Markt eintreten</li></ul><h3>Unsere Werte</h3><ul><li><strong>Qualität:</strong> Wir streben immer nach den höchsten Standards</li><li><strong>Innovation:</strong> Kontinuierliche Entwicklung und Innovation</li><li><strong>Vertrauen:</strong> Transparenter und zuverlässiger Service</li><li><strong>Kundenorientierung:</strong> Kundenzufriedenheit hat Priorität</li></ul></div>')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `description` = VALUES(`description`);

-- 5. Kalite Politikamız
INSERT INTO `pages` (`title`, `slug`, `content`, `meta_title`, `meta_description`, `status`) VALUES
('Kalite Politikamız', 'kalite-politikamiz', '<div class="page-content"><h2>Kalite Politikamız</h2><h3>Kalite Anlayışımız</h3><p>TeknoProje olarak, kaliteyi her şeyin üzerinde tutuyoruz. Platformumuzda yer alan tüm projeler, detaylı bir kalite kontrol sürecinden geçmektedir.</p><h3>Kalite Standartları</h3><ul><li><strong>Kod Kalitesi:</strong> Tüm projeler temiz, okunabilir ve bakımı kolay kod standartlarına uygun olmalıdır</li><li><strong>Dokümantasyon:</strong> Her proje için kapsamlı dokümantasyon sağlanmalıdır</li><li><strong>Test:</strong> Projeler test edilmiş ve çalışır durumda olmalıdır</li><li><strong>Güvenlik:</strong> Güvenlik açıkları kontrol edilir ve düzeltilir</li></ul><h3>Kalite Kontrol Süreci</h3><ol><li>Proje gönderimi</li><li>Otomatik kod analizi</li><li>Manuel inceleme</li><li>Test süreci</li><li>Onay veya geri bildirim</li></ol><h3>Sürekli İyileştirme</h3><p>Kalite standartlarımızı sürekli gözden geçiriyor ve iyileştiriyoruz. Kullanıcı geri bildirimlerini dikkate alarak platformumuzu geliştirmeye devam ediyoruz.</p></div>', 'Kalite Politikamız - TeknoProje', 'TeknoProje kalite politikası. Kalite standartlarımız ve kontrol süreçlerimiz hakkında bilgi.', 'active')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `content` = VALUES(`content`),
    `meta_title` = VALUES(`meta_title`),
    `meta_description` = VALUES(`meta_description`),
    `status` = VALUES(`status`);

SET @page_id_5 = (SELECT id FROM pages WHERE slug = 'kalite-politikamiz' LIMIT 1);

INSERT INTO `content_translations` (`content_id`, `content_type`, `language_code`, `title`, `description`) VALUES
(@page_id_5, 'page', 'tr', 'Kalite Politikamız', '<div class="page-content"><h2>Kalite Politikamız</h2><h3>Kalite Anlayışımız</h3><p>TeknoProje olarak, kaliteyi her şeyin üzerinde tutuyoruz. Platformumuzda yer alan tüm projeler, detaylı bir kalite kontrol sürecinden geçmektedir.</p><h3>Kalite Standartları</h3><ul><li><strong>Kod Kalitesi:</strong> Tüm projeler temiz, okunabilir ve bakımı kolay kod standartlarına uygun olmalıdır</li><li><strong>Dokümantasyon:</strong> Her proje için kapsamlı dokümantasyon sağlanmalıdır</li><li><strong>Test:</strong> Projeler test edilmiş ve çalışır durumda olmalıdır</li><li><strong>Güvenlik:</strong> Güvenlik açıkları kontrol edilir ve düzeltilir</li></ul><h3>Kalite Kontrol Süreci</h3><ol><li>Proje gönderimi</li><li>Otomatik kod analizi</li><li>Manuel inceleme</li><li>Test süreci</li><li>Onay veya geri bildirim</li></ol><h3>Sürekli İyileştirme</h3><p>Kalite standartlarımızı sürekli gözden geçiriyor ve iyileştiriyoruz. Kullanıcı geri bildirimlerini dikkate alarak platformumuzu geliştirmeye devam ediyoruz.</p></div>'),
(@page_id_5, 'page', 'en', 'Quality Policy', '<div class="page-content"><h2>Quality Policy</h2><h3>Our Quality Understanding</h3><p>As TeknoProje, we prioritize quality above everything. All projects on our platform go through a detailed quality control process.</p><h3>Quality Standards</h3><ul><li><strong>Code Quality:</strong> All projects must comply with clean, readable, and maintainable code standards</li><li><strong>Documentation:</strong> Comprehensive documentation must be provided for each project</li><li><strong>Testing:</strong> Projects must be tested and functional</li><li><strong>Security:</strong> Security vulnerabilities are checked and fixed</li></ul><h3>Quality Control Process</h3><ol><li>Project submission</li><li>Automatic code analysis</li><li>Manual review</li><li>Testing process</li><li>Approval or feedback</li></ol><h3>Continuous Improvement</h3><p>We continuously review and improve our quality standards. We continue to develop our platform by taking user feedback into account.</p></div>'),
(@page_id_5, 'page', 'de', 'Qualitätspolitik', '<div class="page-content"><h2>Qualitätspolitik</h2><h3>Unser Qualitätsverständnis</h3><p>Als TeknoProje stellen wir Qualität über alles. Alle Projekte auf unserer Plattform durchlaufen einen detaillierten Qualitätskontrollprozess.</p><h3>Qualitätsstandards</h3><ul><li><strong>Codequalität:</strong> Alle Projekte müssen sauberen, lesbaren und wartbaren Codestandards entsprechen</li><li><strong>Dokumentation:</strong> Für jedes Projekt muss eine umfassende Dokumentation bereitgestellt werden</li><li><strong>Tests:</strong> Projekte müssen getestet und funktionsfähig sein</li><li><strong>Sicherheit:</strong> Sicherheitslücken werden überprüft und behoben</li></ul><h3>Qualitätskontrollprozess</h3><ol><li>Projekteinreichung</li><li>Automatische Codeanalyse</li><li>Manuelle Überprüfung</li><li>Testprozess</li><li>Genehmigung oder Feedback</li></ol><h3>Kontinuierliche Verbesserung</h3><p>Wir überprüfen und verbessern unsere Qualitätsstandards kontinuierlich. Wir entwickeln unsere Plattform weiter, indem wir Benutzerfeedback berücksichtigen.</p></div>')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `description` = VALUES(`description`);

-- 6. Teslimat ve İade Şartları
INSERT INTO `pages` (`title`, `slug`, `content`, `meta_title`, `meta_description`, `status`) VALUES
('Teslimat ve İade Şartları', 'teslimat-ve-iade-sartlari', '<div class="page-content"><h2>Teslimat ve İade Şartları</h2><h3>Teslimat Süreci</h3><p>Satın aldığınız dijital ürünler, ödeme onayından sonra otomatik olarak hesabınıza eklenir. İndirme linkleri ve erişim bilgileri e-posta adresinize gönderilir.</p><h3>Teslimat Süresi</h3><ul><li><strong>Dijital Ürünler:</strong> Anında teslimat</li><li><strong>Özel Geliştirme:</strong> Proje kapsamına göre 7-30 gün</li><li><strong>Danışmanlık:</strong> Randevu ile belirlenir</li></ul><h3>İade Politikası</h3><p>Dijital ürünler için 14 gün içinde iade talebinde bulunabilirsiniz. İade koşulları:</p><ul><li>Ürün indirilmemiş veya kullanılmamış olmalıdır</li><li>İade talebi satın alma tarihinden itibaren 14 gün içinde yapılmalıdır</li><li>İade işlemi 5-7 iş günü içinde tamamlanır</li></ul><h3>İade Edilemeyen Ürünler</h3><ul><li>Özelleştirilmiş projeler</li><li>Kullanılmış veya indirilmiş dijital ürünler</li><li>Danışmanlık hizmetleri (tamamlanmışsa)</li></ul><h3>İade İşlemi</h3><p>İade talebinizi destek sistemimiz üzerinden oluşturabilirsiniz. Destek ekibimiz en kısa sürede talebinizi değerlendirecektir.</p></div>', 'Teslimat ve İade Şartları - TeknoProje', 'TeknoProje teslimat ve iade şartları. Dijital ürün teslimat süreci ve iade politikası.', 'active')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `content` = VALUES(`content`),
    `meta_title` = VALUES(`meta_title`),
    `meta_description` = VALUES(`meta_description`),
    `status` = VALUES(`status`);

SET @page_id_6 = (SELECT id FROM pages WHERE slug = 'teslimat-ve-iade-sartlari' LIMIT 1);

INSERT INTO `content_translations` (`content_id`, `content_type`, `language_code`, `title`, `description`) VALUES
(@page_id_6, 'page', 'tr', 'Teslimat ve İade Şartları', '<div class="page-content"><h2>Teslimat ve İade Şartları</h2><h3>Teslimat Süreci</h3><p>Satın aldığınız dijital ürünler, ödeme onayından sonra otomatik olarak hesabınıza eklenir. İndirme linkleri ve erişim bilgileri e-posta adresinize gönderilir.</p><h3>Teslimat Süresi</h3><ul><li><strong>Dijital Ürünler:</strong> Anında teslimat</li><li><strong>Özel Geliştirme:</strong> Proje kapsamına göre 7-30 gün</li><li><strong>Danışmanlık:</strong> Randevu ile belirlenir</li></ul><h3>İade Politikası</h3><p>Dijital ürünler için 14 gün içinde iade talebinde bulunabilirsiniz. İade koşulları:</p><ul><li>Ürün indirilmemiş veya kullanılmamış olmalıdır</li><li>İade talebi satın alma tarihinden itibaren 14 gün içinde yapılmalıdır</li><li>İade işlemi 5-7 iş günü içinde tamamlanır</li></ul><h3>İade Edilemeyen Ürünler</h3><ul><li>Özelleştirilmiş projeler</li><li>Kullanılmış veya indirilmiş dijital ürünler</li><li>Danışmanlık hizmetleri (tamamlanmışsa)</li></ul><h3>İade İşlemi</h3><p>İade talebinizi destek sistemimiz üzerinden oluşturabilirsiniz. Destek ekibimiz en kısa sürede talebinizi değerlendirecektir.</p></div>'),
(@page_id_6, 'page', 'en', 'Delivery and Refund Terms', '<div class="page-content"><h2>Delivery and Refund Terms</h2><h3>Delivery Process</h3><p>Digital products you purchase are automatically added to your account after payment confirmation. Download links and access information are sent to your email address.</p><h3>Delivery Time</h3><ul><li><strong>Digital Products:</strong> Instant delivery</li><li><strong>Custom Development:</strong> 7-30 days depending on project scope</li><li><strong>Consulting:</strong> Determined by appointment</li></ul><h3>Refund Policy</h3><p>You can request a refund for digital products within 14 days. Refund conditions:</p><ul><li>The product must not be downloaded or used</li><li>Refund request must be made within 14 days from the purchase date</li><li>Refund process is completed within 5-7 business days</li></ul><h3>Non-Refundable Products</h3><ul><li>Customized projects</li><li>Used or downloaded digital products</li><li>Consulting services (if completed)</li></ul><h3>Refund Process</h3><p>You can create your refund request through our support system. Our support team will evaluate your request as soon as possible.</p></div>'),
(@page_id_6, 'page', 'de', 'Liefer- und Rückerstattungsbedingungen', '<div class="page-content"><h2>Liefer- und Rückerstattungsbedingungen</h2><h3>Lieferprozess</h3><p>Digitale Produkte, die Sie kaufen, werden nach Zahlungsbestätigung automatisch Ihrem Konto hinzugefügt. Download-Links und Zugriffsinformationen werden an Ihre E-Mail-Adresse gesendet.</p><h3>Lieferzeit</h3><ul><li><strong>Digitale Produkte:</strong> Sofortige Lieferung</li><li><strong>Individuelle Entwicklung:</strong> 7-30 Tage je nach Projektumfang</li><li><strong>Beratung:</strong> Wird durch Termin bestimmt</li></ul><h3>Rückerstattungsrichtlinie</h3><p>Sie können innerhalb von 14 Tagen eine Rückerstattung für digitale Produkte beantragen. Rückerstattungsbedingungen:</p><ul><li>Das Produkt darf nicht heruntergeladen oder verwendet worden sein</li><li>Rückerstattungsantrag muss innerhalb von 14 Tagen ab Kaufdatum gestellt werden</li><li>Rückerstattungsprozess wird innerhalb von 5-7 Werktagen abgeschlossen</li></ul><h3>Nicht erstattungsfähige Produkte</h3><ul><li>Angepasste Projekte</li><li>Verwendete oder heruntergeladene digitale Produkte</li><li>Beratungsdienstleistungen (wenn abgeschlossen)</li></ul><h3>Rückerstattungsprozess</h3><p>Sie können Ihren Rückerstattungsantrag über unser Support-System erstellen. Unser Support-Team wird Ihren Antrag so schnell wie möglich prüfen.</p></div>')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `description` = VALUES(`description`);

-- 7. Çerez Politikası
INSERT INTO `pages` (`title`, `slug`, `content`, `meta_title`, `meta_description`, `status`) VALUES
('Çerez Politikası', 'cerez-politikasi', '<div class="page-content"><h2>Çerez Politikası</h2><p>Son güncelleme: 2024</p><h3>Çerez Nedir?</h3><p>Çerezler, web sitelerini ziyaret ettiğinizde tarayıcınıza kaydedilen küçük metin dosyalarıdır. Bu dosyalar, web sitesinin daha iyi çalışmasını ve kullanıcı deneyimini iyileştirmesini sağlar.</p><h3>Çerez Türleri</h3><ul><li><strong>Zorunlu Çerezler:</strong> Web sitesinin temel işlevlerini yerine getirmesi için gereklidir</li><li><strong>Performans Çerezleri:</strong> Web sitesinin performansını analiz etmek için kullanılır</li><li><strong>İşlevsellik Çerezleri:</strong> Kullanıcı tercihlerini hatırlamak için kullanılır</li><li><strong>Hedefleme Çerezleri:</strong> Reklam ve pazarlama amaçlı kullanılır</li></ul><h3>Çerez Kullanımımız</h3><p>Platformumuz aşağıdaki amaçlar için çerezler kullanmaktadır:</p><ul><li>Oturum yönetimi ve güvenlik</li><li>Kullanıcı tercihlerini hatırlama</li><li>Site performansını analiz etme</li><li>Kişiselleştirilmiş içerik sunma</li></ul><h3>Çerez Yönetimi</h3><p>Tarayıcı ayarlarınızdan çerezleri yönetebilir veya silebilirsiniz. Ancak, bazı çerezlerin devre dışı bırakılması web sitesinin bazı özelliklerinin çalışmamasına neden olabilir.</p><h3>Üçüncü Taraf Çerezler</h3><p>Platformumuz, analiz ve pazarlama amaçlı üçüncü taraf hizmetler kullanmaktadır. Bu hizmetler kendi çerez politikalarına sahiptir.</p></div>', 'Çerez Politikası - TeknoProje', 'TeknoProje çerez politikası. Çerez kullanımımız ve yönetimi hakkında bilgi.', 'active')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `content` = VALUES(`content`),
    `meta_title` = VALUES(`meta_title`),
    `meta_description` = VALUES(`meta_description`),
    `status` = VALUES(`status`);

SET @page_id_7 = (SELECT id FROM pages WHERE slug = 'cerez-politikasi' LIMIT 1);

INSERT INTO `content_translations` (`content_id`, `content_type`, `language_code`, `title`, `description`) VALUES
(@page_id_7, 'page', 'tr', 'Çerez Politikası', '<div class="page-content"><h2>Çerez Politikası</h2><p>Son güncelleme: 2024</p><h3>Çerez Nedir?</h3><p>Çerezler, web sitelerini ziyaret ettiğinizde tarayıcınıza kaydedilen küçük metin dosyalarıdır. Bu dosyalar, web sitesinin daha iyi çalışmasını ve kullanıcı deneyimini iyileştirmesini sağlar.</p><h3>Çerez Türleri</h3><ul><li><strong>Zorunlu Çerezler:</strong> Web sitesinin temel işlevlerini yerine getirmesi için gereklidir</li><li><strong>Performans Çerezleri:</strong> Web sitesinin performansını analiz etmek için kullanılır</li><li><strong>İşlevsellik Çerezleri:</strong> Kullanıcı tercihlerini hatırlamak için kullanılır</li><li><strong>Hedefleme Çerezleri:</strong> Reklam ve pazarlama amaçlı kullanılır</li></ul><h3>Çerez Kullanımımız</h3><p>Platformumuz aşağıdaki amaçlar için çerezler kullanmaktadır:</p><ul><li>Oturum yönetimi ve güvenlik</li><li>Kullanıcı tercihlerini hatırlama</li><li>Site performansını analiz etme</li><li>Kişiselleştirilmiş içerik sunma</li></ul><h3>Çerez Yönetimi</h3><p>Tarayıcı ayarlarınızdan çerezleri yönetebilir veya silebilirsiniz. Ancak, bazı çerezlerin devre dışı bırakılması web sitesinin bazı özelliklerinin çalışmamasına neden olabilir.</p><h3>Üçüncü Taraf Çerezler</h3><p>Platformumuz, analiz ve pazarlama amaçlı üçüncü taraf hizmetler kullanmaktadır. Bu hizmetler kendi çerez politikalarına sahiptir.</p></div>'),
(@page_id_7, 'page', 'en', 'Cookie Policy', '<div class="page-content"><h2>Cookie Policy</h2><p>Last updated: 2024</p><h3>What are Cookies?</h3><p>Cookies are small text files that are saved to your browser when you visit websites. These files help the website work better and improve user experience.</p><h3>Types of Cookies</h3><ul><li><strong>Essential Cookies:</strong> Required for the website to perform basic functions</li><li><strong>Performance Cookies:</strong> Used to analyze website performance</li><li><strong>Functionality Cookies:</strong> Used to remember user preferences</li><li><strong>Targeting Cookies:</strong> Used for advertising and marketing purposes</li></ul><h3>Our Cookie Usage</h3><p>Our platform uses cookies for the following purposes:</p><ul><li>Session management and security</li><li>Remembering user preferences</li><li>Analyzing site performance</li><li>Providing personalized content</li></ul><h3>Cookie Management</h3><p>You can manage or delete cookies from your browser settings. However, disabling some cookies may cause some website features to not work.</p><h3>Third-Party Cookies</h3><p>Our platform uses third-party services for analytics and marketing purposes. These services have their own cookie policies.</p></div>'),
(@page_id_7, 'page', 'de', 'Cookie-Richtlinie', '<div class="page-content"><h2>Cookie-Richtlinie</h2><p>Letzte Aktualisierung: 2024</p><h3>Was sind Cookies?</h3><p>Cookies sind kleine Textdateien, die in Ihrem Browser gespeichert werden, wenn Sie Websites besuchen. Diese Dateien helfen der Website, besser zu funktionieren und die Benutzererfahrung zu verbessern.</p><h3>Cookie-Arten</h3><ul><li><strong>Notwendige Cookies:</strong> Erforderlich, damit die Website grundlegende Funktionen ausführen kann</li><li><strong>Leistungs-Cookies:</strong> Werden zur Analyse der Website-Leistung verwendet</li><li><strong>Funktions-Cookies:</strong> Werden verwendet, um Benutzereinstellungen zu speichern</li><li><strong>Targeting-Cookies:</strong> Werden für Werbe- und Marketingzwecke verwendet</li></ul><h3>Unsere Cookie-Nutzung</h3><p>Unsere Plattform verwendet Cookies für folgende Zwecke:</p><ul><li>Sitzungsverwaltung und Sicherheit</li><li>Speichern von Benutzereinstellungen</li><li>Analyse der Website-Leistung</li><li>Bereitstellung personalisierter Inhalte</li></ul><h3>Cookie-Verwaltung</h3><p>Sie können Cookies in Ihren Browser-Einstellungen verwalten oder löschen. Das Deaktivieren einiger Cookies kann jedoch dazu führen, dass einige Website-Funktionen nicht funktionieren.</p><h3>Cookies von Drittanbietern</h3><p>Unsere Plattform verwendet Drittanbieterdienste für Analyse- und Marketingzwecke. Diese Dienste haben ihre eigenen Cookie-Richtlinien.</p></div>')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `description` = VALUES(`description`);

-- 8. Lisans Politikası
INSERT INTO `pages` (`title`, `slug`, `content`, `meta_title`, `meta_description`, `status`) VALUES
('Lisans Politikası', 'lisans-politikasi', '<div class="page-content"><h2>Lisans Politikası</h2><p>Son güncelleme: 2024</p><h3>Lisans Türleri</h3><p>Platformumuzda satılan projeler farklı lisans türlerine sahip olabilir:</p><ul><li><strong>Tek Kullanımlık Lisans:</strong> Projeyi sadece bir kez kullanabilirsiniz</li><li><strong>Çoklu Kullanım Lisansı:</strong> Projeyi sınırlı sayıda projede kullanabilirsiniz</li><li><strong>Genişletilmiş Lisans:</strong> Projeyi sınırsız sayıda projede kullanabilirsiniz</li><li><strong>Kurumsal Lisans:</strong> Tüm şirket içinde kullanım hakkı</li></ul><h3>Lisans Kapsamı</h3><p>Satın aldığınız lisans türüne göre aşağıdaki haklara sahipsiniz:</p><ul><li>Projeyi kendi projelerinizde kullanma</li><li>Projeyi özelleştirme ve geliştirme</li><li>Müşteri projelerinde kullanma (lisans türüne göre)</li></ul><h3>Yasaklanan Kullanımlar</h3><p>Aşağıdaki kullanımlar kesinlikle yasaktır:</p><ul><li>Projeyi başka platformlarda satmak veya dağıtmak</li><li>Kaynak kodunu paylaşmak (açık kaynak lisanslar hariç)</li><li>Projeyi template marketlerinde satmak</li><li>Telif hakkı ihlali yapmak</li></ul><h3>Lisans İhlali</h3><p>Lisans ihlali tespit edildiğinde, hesabınız askıya alınabilir ve yasal işlem başlatılabilir. Tüm haklarımız saklıdır.</p><h3>İletişim</h3><p>Lisans konularında sorularınız için destek ekibimizle iletişime geçebilirsiniz.</p></div>', 'Lisans Politikası - TeknoProje', 'TeknoProje lisans politikası. Proje lisans türleri ve kullanım hakları hakkında bilgi.', 'active')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `content` = VALUES(`content`),
    `meta_title` = VALUES(`meta_title`),
    `meta_description` = VALUES(`meta_description`),
    `status` = VALUES(`status`);

SET @page_id_8 = (SELECT id FROM pages WHERE slug = 'lisans-politikasi' LIMIT 1);

INSERT INTO `content_translations` (`content_id`, `content_type`, `language_code`, `title`, `description`) VALUES
(@page_id_8, 'page', 'tr', 'Lisans Politikası', '<div class="page-content"><h2>Lisans Politikası</h2><p>Son güncelleme: 2024</p><h3>Lisans Türleri</h3><p>Platformumuzda satılan projeler farklı lisans türlerine sahip olabilir:</p><ul><li><strong>Tek Kullanımlık Lisans:</strong> Projeyi sadece bir kez kullanabilirsiniz</li><li><strong>Çoklu Kullanım Lisansı:</strong> Projeyi sınırlı sayıda projede kullanabilirsiniz</li><li><strong>Genişletilmiş Lisans:</strong> Projeyi sınırsız sayıda projede kullanabilirsiniz</li><li><strong>Kurumsal Lisans:</strong> Tüm şirket içinde kullanım hakkı</li></ul><h3>Lisans Kapsamı</h3><p>Satın aldığınız lisans türüne göre aşağıdaki haklara sahipsiniz:</p><ul><li>Projeyi kendi projelerinizde kullanma</li><li>Projeyi özelleştirme ve geliştirme</li><li>Müşteri projelerinde kullanma (lisans türüne göre)</li></ul><h3>Yasaklanan Kullanımlar</h3><p>Aşağıdaki kullanımlar kesinlikle yasaktır:</p><ul><li>Projeyi başka platformlarda satmak veya dağıtmak</li><li>Kaynak kodunu paylaşmak (açık kaynak lisanslar hariç)</li><li>Projeyi template marketlerinde satmak</li><li>Telif hakkı ihlali yapmak</li></ul><h3>Lisans İhlali</h3><p>Lisans ihlali tespit edildiğinde, hesabınız askıya alınabilir ve yasal işlem başlatılabilir. Tüm haklarımız saklıdır.</p><h3>İletişim</h3><p>Lisans konularında sorularınız için destek ekibimizle iletişime geçebilirsiniz.</p></div>'),
(@page_id_8, 'page', 'en', 'License Policy', '<div class="page-content"><h2>License Policy</h2><p>Last updated: 2024</p><h3>License Types</h3><p>Projects sold on our platform may have different license types:</p><ul><li><strong>Single Use License:</strong> You can use the project only once</li><li><strong>Multiple Use License:</strong> You can use the project in a limited number of projects</li><li><strong>Extended License:</strong> You can use the project in unlimited projects</li><li><strong>Enterprise License:</strong> Right to use within the entire company</li></ul><h3>License Scope</h3><p>Depending on the license type you purchase, you have the following rights:</p><ul><li>Use the project in your own projects</li><li>Customize and develop the project</li><li>Use in client projects (depending on license type)</li></ul><h3>Prohibited Uses</h3><p>The following uses are strictly prohibited:</p><ul><li>Selling or distributing the project on other platforms</li><li>Sharing source code (except open source licenses)</li><li>Selling the project on template marketplaces</li><li>Copyright infringement</li></ul><h3>License Violation</h3><p>When a license violation is detected, your account may be suspended and legal action may be initiated. All rights reserved.</p><h3>Contact</h3><p>You can contact our support team for questions about licensing.</p></div>'),
(@page_id_8, 'page', 'de', 'Lizenzrichtlinie', '<div class="page-content"><h2>Lizenzrichtlinie</h2><p>Letzte Aktualisierung: 2024</p><h3>Lizenztypen</h3><p>Projekte, die auf unserer Plattform verkauft werden, können verschiedene Lizenztypen haben:</p><ul><li><strong>Einzelnutzungslizenz:</strong> Sie können das Projekt nur einmal verwenden</li><li><strong>Mehrfachnutzungslizenz:</strong> Sie können das Projekt in einer begrenzten Anzahl von Projekten verwenden</li><li><strong>Erweiterte Lizenz:</strong> Sie können das Projekt in unbegrenzten Projekten verwenden</li><li><strong>Unternehmenslizenz:</strong> Recht zur Nutzung im gesamten Unternehmen</li></ul><h3>Lizenzumfang</h3><p>Je nach dem von Ihnen erworbenen Lizenztyp haben Sie folgende Rechte:</p><ul><li>Verwenden Sie das Projekt in Ihren eigenen Projekten</li><li>Projekt anpassen und entwickeln</li><li>Verwendung in Kundenprojekten (je nach Lizenztyp)</li></ul><h3>Verbotene Verwendungen</h3><p>Folgende Verwendungen sind strengstens verboten:</p><ul><li>Verkauf oder Verteilung des Projekts auf anderen Plattformen</li><li>Quellcode teilen (außer Open-Source-Lizenzen)</li><li>Verkauf des Projekts auf Template-Marktplätzen</li><li>Urheberrechtsverletzung</li></ul><h3>Lizenzverletzung</h3><p>Wenn eine Lizenzverletzung festgestellt wird, kann Ihr Konto gesperrt werden und rechtliche Schritte eingeleitet werden. Alle Rechte vorbehalten.</p><h3>Kontakt</h3><p>Sie können sich für Fragen zur Lizenzierung an unser Support-Team wenden.</p></div>')
ON DUPLICATE KEY UPDATE 
    `title` = VALUES(`title`),
    `description` = VALUES(`description`);

