-- Proje 16: EN/DE tam açıklama güncellemesi (kısa çeviri düzeltmesi)
-- mysql -u teknopro -p teknopro < database_project_oyun_webotonom_update_descriptions.sql

USE `teknopro`;

UPDATE `content_translations` SET
  `description` = 'German Verb Card Game is a free, open-source web application for learning German. It teaches 500+ verbs in a fun, competitive card game format — playable offline alone or in real time with friends.\n\n## Modules and Features\n\n### Game Modes\n- **Single Player (Offline):** No internet required. 1–4 players on one device (pass & play). Difficulty from A1 to C1.\n- **Multiplayer (Online):** Real-time WebSocket via Socket.io. Create a lobby, share the room code, play with up to 4 players. Answers are validated on the server.\n\n### Question Bank\n- 500+ German verbs, 4-option multiple choice\n- A1 (Beginner) to C1 (Advanced) level filters\n- Questions and options shuffled each round\n- Question language: Turkish, German, Ukrainian, Arabic\n\n### Lobby Management\n- Create/join rooms with UUID\n- Host sets question count, time limit, max players\n- Ready system: game starts when everyone is ready\n- Host transfer if the host leaves\n\n### Timing and Turns\n- Turn-based play: only the active player can answer\n- Independent client timers to avoid sync drift\n- Server auto-skips on timeout (player_timeout)\n- Combo multiplier for consecutive correct answers\n\n### Progress and Profile\n- XP & levels from correct answers and game results\n- Badges unlocked by level\n- Achievements for special goals\n- Daily quests and streak tracking\n- Leaderboards (weekly/monthly)\n\n### Store and Premium\n- Bronze, Silver, Gold premium packages\n- Custom frames and power-ups (time bonus, mistake shield, time freeze)\n- Friend invites\n\n### PWA and Mobile\n- Install to home screen, splash screen, adaptive icons\n- Service Worker offline cache\n- Android APK via PWABuilder\n- Fully responsive layout\n\n### Real-Time Chat\n- In-lobby messaging via Socket.io\n- Messages filtered and sent only to the current lobby\n\n## Technical Stack\n- **Frontend:** Vanilla HTML5, CSS3, JavaScript ES6+\n- **Backend:** Node.js, Express.js\n- **Real-Time:** Socket.io (WebSocket)\n- **PWA:** Service Worker, Web App Manifest\n- **Live:** https://game.webotonom.de/',
  `short_description` = 'Learn German verbs in a fun card game. Single and multiplayer modes, XP system, PWA — works on any device.'
WHERE `content_id` = 16 AND `content_type` = 'project' AND `language_code` = 'en';

UPDATE `content_translations` SET
  `description` = 'Deutsches Verb-Kartenspiel ist eine kostenlose Open-Source-Web-App zum Deutschlernen. Über 500 Verben werden im Kartenspiel-Format spielerisch und wettbewerbsorientiert vermittelt — offline allein oder in Echtzeit mit Freunden.\n\n## Module und Funktionen\n\n### Spielmodi\n- **Einzelspieler (Offline):** Kein Internet nötig. 1–4 Spieler auf einem Gerät (Pass & Play). Schwierigkeit A1 bis C1.\n- **Mehrspieler (Online):** Echtzeit-WebSocket mit Socket.io. Lobby erstellen, Code teilen, bis zu 4 Spieler. Antworten werden serverseitig geprüft.\n\n### Fragenbank\n- 500+ deutsche Verben, Multiple Choice mit 4 Optionen\n- Stufenfilter A1 (Anfänger) bis C1 (Fortgeschritten)\n- Zufällige Mischung von Fragen und Antworten\n- Fragensprache: Türkisch, Deutsch, Ukrainisch, Arabisch\n\n### Lobby-Verwaltung\n- Räume per UUID erstellen und beitreten\n- Host legt Fragenanzahl, Zeitlimit und Maximalspieler fest\n- Ready-System: Start erst wenn alle bereit sind\n- Host-Wechsel wenn der Ersteller die Lobby verlässt\n\n### Zeit und Züge\n- Rundenbasiert: nur der aktive Spieler antwortet\n- Unabhängige Client-Timer gegen Sync-Fehler\n- Server überspringt bei Zeitablauf (player_timeout)\n- Combo-Multiplikator bei Serien richtiger Antworten\n\n### Fortschritt und Profil\n- XP & Level durch richtige Antworten und Spielende\n- Abzeichen je nach Level\n- Erfolge für besondere Aufgaben\n- Tägliche Quests und Streak\n- Bestenlisten (wöchentlich/monatlich)\n\n### Shop und Premium\n- Bronze-, Silver-, Gold-Pakete\n- Rahmen und Power-ups (Zeitbonus, Fehlerschutz, Zeitstopp)\n- Freunde einladen\n\n### PWA und Mobil\n- Installation auf dem Startbildschirm, Splash, adaptive Icons\n- Offline-Cache per Service Worker\n- Android-APK über PWABuilder\n- Responsives Design\n\n### Echtzeit-Chat\n- Lobby-Chat über Socket.io\n- Nachrichten nur an die aktuelle Lobby\n\n## Technische Basis\n- **Frontend:** Vanilla HTML5, CSS3, JavaScript ES6+\n- **Backend:** Node.js, Express.js\n- **Echtzeit:** Socket.io (WebSocket)\n- **PWA:** Service Worker, Web App Manifest\n- **Live:** https://game.webotonom.de/',
  `short_description` = 'Deutsche Verben spielerisch lernen. Einzel- und Mehrspielermodus, XP, PWA — auf jedem Gerät.'
WHERE `content_id` = 16 AND `content_type` = 'project' AND `language_code` = 'de';

UPDATE `content_translations` SET
  `description` = (SELECT `description` FROM `projects` WHERE `id` = 16 LIMIT 1),
  `short_description` = (SELECT `short_description` FROM `projects` WHERE `id` = 16 LIMIT 1)
WHERE `content_id` = 16 AND `content_type` = 'project' AND `language_code` = 'tr';
